### PR TITLE
Add Turkish translation

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by alexkdeveloper** [comment]
Hi!
Does the translation of lines containing "%s" work for you?
For some reason these lines are not translated into Russian. Maybe this is due to the fact that these are Cyrillic characters and you need to write something for them in meson.build?
The remaining lines that do not contain "%s" are translated normally. I have not encountered such a problem yet. At the moment I have left the ru.po file unchanged.

**Comment by ghost** [comment]
Unfortunately it's not working for me either. Could you fix it?

**Comment by alexkdeveloper** [comment]
At the moment I do not know how to fix it. Do you have any ideas?

**Comment by alexkdeveloper** [comment]
I have not found a solution to this problem. 
The only way out at the moment is to rewrite the lines without the "%s" character.
But then you will have to edit the translation file for your language.
Perhaps you have another solution?

**Comment by alexkdeveloper** [comment]
I have removed the character "%s" from the message lines. 
Everything should work now. 
You will need to edit your translation file according to the changes I have made.

**Comment by ghost** [comment]
Updated. Could you consider creating a pot file. It's not easy to manage translations without a pot file.

**Comment by alexkdeveloper** [comment]
It's possible. 
If you have such an opportunity, then you can create a pull request with a ready-made pot file. 
I will definitely accept it)

**Pull request merged**
